# Generated by Django 4.1.dev20211213175307 on 2022-02-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
