# Generated by Django 4.1.dev20211213175307 on 2022-02-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory_remove_guitar_year_guitar_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stringing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateField()),
                ('brand', models.CharField(max_length=50)),
                ('gauge', models.CharField(choices=[('E', 'Extra-Light'), ('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], default='L', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
