# Generated by Django 4.1.dev20211213175307 on 2022-02-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0004_alter_stringing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
